// Generated by rkb install; changes are overwritten. Remove with: rkb install --uninstall __HARNESS__
//
// Forwards __HARNESS__ events to `rkb hook <event>` as Claude Code shaped payloads and turns the
// replies back into results. All rkb logic lives in the rkb binary; this file only maps.
import { spawn } from "node:child_process";

const HARNESS = "__HARNESS__";
const TIMEOUT_MS = 5000;
// Kept here as well so a command that runs `rkb confirm` is gated even when `rkb` cannot run.
const CONFIRM = /(^|[\s;&|('"/])rkb\s+confirm\b/;
const NO_UI = "rkb confirm needs the user: ask them to run this command in their own terminal.";
const DECLINED = "The user declined this rkb confirm.";
// omp stops a session_shutdown handler after 2 s.
const SHUTDOWN_TIMEOUT_MS = 1800;
// The /rkb-retro and /rkb-distill prompts; rkb install fills them in.
const RETRO: string = "__RETRO__";
const DISTILL: string = "__DISTILL__";

process.env.RKB_HARNESS = HARNESS;

function hook(event: string, payload: Record<string, unknown>, timeoutMs = TIMEOUT_MS): Promise<string | undefined> {
  return new Promise((resolve) => {
    let out = "";
    let done = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const finish = (value?: string) => {
      if (done) return;
      done = true;
      if (timer) clearTimeout(timer);
      resolve(value);
    };
    let child: any;
    try {
      child = spawn("rkb", ["hook", event, "--harness", HARNESS], { stdio: ["pipe", "pipe", "ignore"] });
    } catch {
      return finish();
    }
    timer = setTimeout(() => {
      child.kill("SIGKILL");
      finish();
    }, timeoutMs);
    child.on("error", () => finish());
    child.stdout.on("data", (d: Buffer) => {
      out += d.toString();
    });
    child.on("close", (code: number | null) => finish(code === 0 && out.trim() ? out.trim() : undefined));
    child.stdin.on("error", () => {});
    child.stdin.end(JSON.stringify(payload));
  });
}

function parse(reply: string | undefined): any {
  if (!reply) return undefined;
  try {
    return JSON.parse(reply);
  } catch {
    return undefined;
  }
}

function additional(reply: string | undefined): string | undefined {
  const text = parse(reply)?.hookSpecificOutput?.additionalContext;
  return typeof text === "string" && text ? text : undefined;
}

function base(ctx: any): Record<string, unknown> {
  let session = "";
  try {
    session = String(ctx?.sessionManager?.getSessionId?.() ?? "");
  } catch {}
  return { session_id: session, cwd: String(ctx?.cwd ?? process.cwd()) };
}

function transcript(ctx: any): string | undefined {
  try {
    const file = ctx?.sessionManager?.getSessionFile?.();
    return typeof file === "string" && file ? file : undefined;
  } catch {
    return undefined;
  }
}

function prompt(text: string, args: string): string {
  return text.replace("$ARGUMENTS", args.trim() || "none");
}

function bash(event: any): string | undefined {
  return event?.toolName === "bash" ? String(event?.input?.command ?? "") : undefined;
}

// Claude Code's `error` starts with `Exit code N`; pi and omp end the output with `Command exited with code N`.
function errorText(content: any): string {
  const text = (Array.isArray(content) ? content : [])
    .filter((p: any) => p?.type === "text" && typeof p.text === "string")
    .map((p: any) => p.text)
    .join("\n")
    .replace(/\s+$/, "");
  const lines = text.split("\n");
  const m = /^Command exited with code (\d+)$/.exec((lines[lines.length - 1] ?? "").trim());
  if (!m) return text;
  lines.pop();
  return `Exit code ${m[1]}\n${lines.join("\n").replace(/\s+$/, "")}`;
}

function safe(fn: (event: any, ctx: any) => Promise<any>) {
  return async (event: any, ctx: any) => {
    try {
      return await fn(event, ctx);
    } catch {
      return undefined;
    }
  };
}

export default function rkb(pi: any) {
  let startContext: string | undefined;
  // pi has no stop_hook_active flag, so the extension tracks its own continuation.
  let continuedByRkb = false;

  pi.on(
    "session_start",
    safe(async (event, ctx) => {
      startContext = await hook("session-start", { ...base(ctx), source: String(event?.reason ?? "startup") });
    }),
  );

  pi.on(
    "before_agent_start",
    safe(async () => {
      if (!startContext) return undefined;
      const content = startContext;
      startContext = undefined;
      return { message: { customType: "rkb", content, display: false } };
    }),
  );

  pi.on("tool_call", async (event: any, ctx: any) => {
    const command = bash(event);
    if (command === undefined || !command.includes("rkb")) return undefined;
    const gated = CONFIRM.test(command);
    try {
      const out = parse(await hook("pre-tool", { ...base(ctx), tool_name: "Bash", tool_input: { command } }))?.hookSpecificOutput;
      let reason: string;
      if (out?.permissionDecision === "ask") reason = String(out.permissionDecisionReason ?? "rkb confirm needs your approval");
      else if (gated) reason = "rkb confirm needs your approval";
      else return undefined;
      if (!ctx?.hasUI) return { block: true, reason: NO_UI };
      const yes = await ctx.ui.confirm("rkb confirm", `${reason}\n\nCommand: ${command}`);
      return yes ? undefined : { block: true, reason: DECLINED };
    } catch {
      return gated ? { block: true, reason: NO_UI } : undefined;
    }
  });

  pi.on(
    "tool_result",
    safe(async (event, ctx) => {
      const command = bash(event);
      if (command === undefined) return undefined;
      const payload = { ...base(ctx), tool_name: "Bash", tool_input: { command } };
      if (!event.isError) {
        await hook("tool-ok", payload);
        return undefined;
      }
      const note = additional(await hook("tool-failed", { ...payload, error: errorText(event.content) }));
      if (!note) return undefined;
      return { content: [...(Array.isArray(event.content) ? event.content : []), { type: "text", text: note }] };
    }),
  );

  pi.on(
    "session_before_compact",
    safe(async (_event, ctx) => {
      const path = transcript(ctx);
      if (path) await hook("pre-compact", { ...base(ctx), transcript_path: path });
      return undefined;
    }),
  );

  pi.on(
    "session_shutdown",
    safe(async (event, ctx) => {
      const path = transcript(ctx);
      if (path) await hook("session-end", { ...base(ctx), transcript_path: path, reason: String(event?.reason ?? "") }, SHUTDOWN_TIMEOUT_MS);
      return undefined;
    }),
  );

  for (const [name, text, description] of [
    ["rkb-retro", RETRO, "Record the durable lessons of this session in rkb now"],
    ["rkb-distill", DISTILL, "Turn a few rkb inbox items into lessons"],
  ]) {
    pi.registerCommand(name, {
      description,
      handler: async (args: string) => {
        pi.sendUserMessage(prompt(text, String(args ?? "")));
      },
    });
  }

  pi.on(
    "input",
    safe(async (event, ctx) => {
      continuedByRkb = false;
      await hook("prompt", { ...base(ctx), prompt: String(event?.text ?? "") });
      return HARNESS === "pi" ? { action: "continue" } : undefined;
    }),
  );

  if (HARNESS === "pi") {
    pi.on(
      "agent_before_settle",
      safe(async (event, ctx) => {
        if (event?.outcome !== "completed" || event?.context?.canContinue === false) return undefined;
        const note = additional(await hook("stop", { ...base(ctx), stop_hook_active: continuedByRkb }));
        if (!note) {
          continuedByRkb = false;
          return undefined;
        }
        continuedByRkb = true;
        const entries = Array.isArray(event.entries) ? event.entries : [];
        return { entries: [...entries, { type: "custom_message", customType: "rkb", content: note, display: false }], continue: true };
      }),
    );
  }

  if (HARNESS === "omp") {
    pi.on(
      "session_stop",
      safe(async (event, ctx) => {
        if (event?.signal?.aborted) return undefined;
        const payload = { ...base(ctx), stop_hook_active: Boolean(event?.stop_hook_active) };
        if (event?.session_id) payload.session_id = String(event.session_id);
        const note = additional(await hook("stop", payload));
        return note ? { continue: true, additionalContext: note } : undefined;
      }),
    );
  }
}
