// Generated by rkb install; changes are overwritten. Remove with: rkb install --uninstall claude
//
// Shows rkb's state in Claude Code and runs the observer inside the session. Every decision is
// made by the rkb binary; this module only calls it and draws what it prints.
import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { Hit, InboxRow, Injected, Item, Lesson, Request, Status, View } from '../types'

// The rkb binary that installed this file; rkb install fills it in.
const RKB: string = "__RKB__"
const PANE = 'rkb'
const COMMAND = 'rkb-pane'
const DOT = ' \u00b7 '
const KIND: Record<string, string> = { transcript: 'extract', observed: 'observed', note: 'note' }
const DOT_MARK = '\u25cf'
const ARROW = '\u203a'
const RULE = '\u2500'
const LEVEL: Record<number, { label: string; color?: string }> = {
  3: { label: 'high', color: 'red' },
  2: { label: 'med', color: 'yellow' },
  1: { label: 'low' },
}
const TYPE_COLOR: Record<string, string> = { pitfall: 'red', recipe: 'green', fact: 'cyan', decision: 'magenta', preference: 'yellow' }
const OPEN = { id: PANE, title: 'rkb', focus: true, closeOnEscape: true, columns: 72 } as const

function relevanceColor(r: string | null): string | undefined {
  const n = r === null ? NaN : Number(r)
  if (n >= 0.8) return 'green'
  if (n >= 0.5) return 'yellow'
  return undefined
}
const UI_TIMEOUT_MS = 5000
// A job step parses notes and writes the inbox item, and a prepare reads the transcript.
const JOB_TIMEOUT_MS = 30000
const NOTES_MAX_TOKENS = 4096

const status = atom({ plugin: 'rkb', key: 'status' } as const, null)
const band = atom({ plugin: 'rkb', key: 'band' } as const, [])
const seen = atom({ plugin: 'rkb', key: 'seen' } as const, [])
const view = atom({ plugin: 'rkb', key: 'view' } as const, 'search')
const hits = atom({ plugin: 'rkb', key: 'hits' } as const, [])
const lesson = atom({ plugin: 'rkb', key: 'lesson' } as const, null)
const item = atom({ plugin: 'rkb', key: 'item' } as const, null)
const inbox = atom({ plugin: 'rkb', key: 'inbox' } as const, [])
const note = atom({ plugin: 'rkb', key: 'note' } as const, '')

type Json = Record<string, any>
type Ran = { ok: boolean; data: Json | undefined }
type Session = { id: string; cwd: string; transcript?: string }

/** Runs rkb with JSON output; never throws. `ok` is false when rkb is missing, failed or printed no JSON. */
async function rkb($: EngineInterface, args: string[], opts: { cwd?: string; stdin?: string; timeoutMs?: number } = {}): Promise<Ran> {
  try {
    const r = await $.process.run([RKB, ...args, '--format', 'json'], {
      cwd: opts.cwd,
      stdin: opts.stdin,
      timeoutMs: opts.timeoutMs ?? UI_TIMEOUT_MS,
    })
    let data: Json | undefined
    try {
      data = JSON.parse(r.stdout)
    } catch {
      data = undefined
    }
    return { ok: r.exitCode === 0 && data !== undefined, data }
  } catch {
    return { ok: false, data: undefined }
  }
}

/** `text` on one line, cut to `width` characters with `...`. */
function cut(text: string, width: number): string {
  const line = text.replace(/\s+/g, ' ').trim()
  return line.length <= width ? line : `${line.slice(0, Math.max(0, width - 3))}...`
}

function plural(n: number, word: string): string {
  return `${n} ${word}${n === 1 ? '' : 's'}`
}

export function statusLine(s: Status | null): string | undefined {
  if (!s) return undefined
  const parts: string[] = []
  if (s.inbox > 0) parts.push(`${s.inbox} inbox (${s.high} high)`)
  if (s.curate > 0) parts.push(`${s.curate} curate`)
  if (s.requests.length > 0) parts.push(plural(s.requests.length, 'request'))
  return parts.length === 0 ? undefined : parts.join(DOT)
}

async function refresh($: EngineInterface, session: Session): Promise<void> {
  const r = await rkb($, ['status', '--session', session.id], { cwd: session.cwd })
  if (!r.ok || !r.data) return
  const d = r.data
  const s: Status = {
    inbox: d.inbox?.total ?? 0,
    high: d.inbox?.priority?.['3'] ?? 0,
    curate: d.curate ?? 0,
    requests: (d.requests ?? []).map((q: Json): Request => ({ id: q.id, question: q.question, options: q.options ?? [] })),
  }
  await update($, status, () => s)
  $.ui.status(statusLine(s))
  const injected: Injected[] = (d.injected ?? []).map((i: Json) => ({ id: i.id, title: i.title ?? null, hook: i.hook ?? null }))
  const known = await read($, seen)
  const fresh = injected.filter(i => !known.includes(i.id))
  if (fresh.length > 0) {
    await update($, seen, ids => [...ids, ...fresh.map(i => i.id)])
    await update($, band, shown => [...shown, ...fresh])
  }
}

/** One observer run through model jobs: rkb prepares each part, the session's own client answers it. */
async function observe($: EngineInterface, session: Session): Promise<void> {
  if (!session.transcript) return
  const model = await $.session.model()
  const args = ['job', 'prepare', 'observe', '--session', session.id, '--transcript', session.transcript, '--harness', 'claude-code', '--cwd', session.cwd, '--model', model]
  let step = (await rkb($, args, { cwd: session.cwd, timeoutMs: JOB_TIMEOUT_MS })).data
  while (step?.job && step.prompt) {
    const finish = ['job', 'finish', step.job, '--part', String(step.part)]
    const failures: string[] = []
    let next: Json | undefined
    let answered = false
    for (const m of step.models as { entry: string; model: string | null }[]) {
      const r = await $.model.complete({ model: m.model ?? model, prompt: step.prompt, maxTokens: NOTES_MAX_TOKENS })
      if (r.isAnswered) {
        next = (await rkb($, [...finish, '--model', m.entry], { cwd: session.cwd, stdin: r.text, timeoutMs: JOB_TIMEOUT_MS })).data
        answered = true
        break
      }
      failures.push(`${m.entry}: ${r.reason}`)
    }
    if (!answered) {
      await rkb($, [...finish, '--failed', failures.join('; ')], { cwd: session.cwd })
      return
    }
    if (next?.outcome === 'added') $.ui.toast(`rkb: ${plural(next.notes, 'note')} for the inbox`)
    step = next
  }
}

async function openLesson($: EngineInterface, id: string): Promise<void> {
  const r = await rkb($, ['show', id])
  if (!r.ok || !r.data) {
    $.ui.toast(`rkb: cannot show ${id}`)
    return
  }
  const d = r.data
  const meta = [id, d.frontmatter?.type, d.frontmatter?.status, d.path].filter(Boolean).join(DOT)
  const l: Lesson = { id, title: d.title ?? id, body: d.body ?? '', meta }
  await update($, lesson, () => l)
  await update($, view, () => 'lesson' as View)
  await $.ui.open(OPEN)
}

async function openItem($: EngineInterface, row: InboxRow): Promise<void> {
  const r = await rkb($, ['inbox', 'show', row.id])
  if (!r.ok || !r.data) {
    $.ui.toast(`rkb: cannot show inbox item ${row.id}`)
    return
  }
  const meta = [row.id, KIND[row.kind] ?? row.kind, LEVEL[row.priority]?.label, row.age, r.data.meta?.cwd].filter(Boolean).join(DOT)
  const i: Item = { id: row.id, title: row.preview, body: r.data.body ?? '', meta }
  await update($, item, () => i)
  await update($, view, () => 'item' as View)
}

async function show($: EngineInterface, v: View): Promise<void> {
  if (v === 'inbox') {
    const r = await rkb($, ['inbox'])
    const rows: InboxRow[] = (r.data?.items ?? []).map((i: Json) => ({ id: i.id, kind: i.kind, priority: i.priority, age: i.age, preview: i.preview }))
    await update($, inbox, () => rows)
  }
  await update($, view, () => v)
  if (v === 'search') await $.ui.focus({ requestId: PANE, key: 'query' }).catch(() => undefined)
}

async function answer($: EngineInterface, session: Session, q: Request): Promise<void> {
  let choice: string
  try {
    choice = await $.ui.ask(q.question.endsWith('?') ? q.question : `${q.question}?`, { options: q.options.slice(0, 4), header: 'rkb' })
  } catch {
    return
  }
  const r = await rkb($, ['confirm', q.id, '--choice', choice], { cwd: session.cwd })
  const d = r.data ?? {}
  $.ui.toast(r.ok ? `rkb: ${d.id ? `${d.id} ` : ''}${d.message ?? d.status ?? 'done'}` : `rkb: ${d.error?.message ?? 'confirm failed'}`)
  await refresh($, session)
}

type Live = { session?: Session; isOff: boolean; isObserving: boolean }

/** Runs `work` after the current dispatch, so a turn or a compaction never waits for it. */
function later($: EngineInterface, work: () => Promise<void>): void {
  $.clock.after(0, () => {
    void work().catch(() => undefined)
  })
}

function turnEnded($: EngineInterface, live: Live, e: { session_id: string; cwd: string; transcript_path: string }): void {
  const s: Session = { id: e.session_id, cwd: e.cwd, transcript: e.transcript_path }
  live.session = s
  later($, async () => {
    await refresh($, s)
    if (live.isObserving) return
    live.isObserving = true
    try {
      await observe($, s)
    } finally {
      live.isObserving = false
    }
  })
}

export const register: Register = on => {
  const live: Live = { isOff: false, isObserving: false }

  on('session.start', async ($, e, next) => {
    live.isOff = Boolean(await $.env.get('RKB_OBSERVER'))
    if (!live.isOff) {
      const s: Session = { id: await $.session.id(), cwd: e.cwd }
      live.session = s
      // `/rkb` belongs to the plugin's skill, so Claude Code refuses it for a mod command.
      await $.command
        .register({ name: COMMAND, description: 'Search lessons, read the inbox and answer rkb requests in a pane' })
        .catch(() => undefined)
      later($, () => refresh($, s))
    }
    return next(e)
  })

  on('classic.Stop', async ($, e, next) => {
    const r = await next(e)
    if (!live.isOff) turnEnded($, live, e)
    return r
  })

  on('classic.PreCompact', async ($, e, next) => {
    if (!live.isOff) turnEnded($, live, e)
    return next(e)
  })

  on('prompt.submit', async ($, e, next) => {
    if (!live.isOff) await update($, band, () => [])
    return next(e)
  })

  on('command.run', { command: COMMAND }, async $ => {
    await $.ui.open(OPEN)
    return {}
  })

  on('ui.render', { component: 'AbovePrompt' }, async ($, e, next) => {
    const shown = await read($, band)
    if (shown.length === 0) return next(e)
    const { Box, Button, Text } = $.ui.resolve(e)
    const drop = (id: string) => update($, band, list => list.filter(i => i.id !== id))
    return (
      <Box flexDirection="column">
        {shown.map(i => (
          <Box key={`lesson-${i.id}`} gap={1}>
            <Text color="cyan">{ARROW} rkb</Text>
            <Text dimColor>{i.hook ?? 'hook'}</Text>
            <Text>{i.title ?? i.id}</Text>
            <Text dimColor>{i.id}</Text>
            <Button key={`open-${i.id}`} label="Open" onPress={() => openLesson($, i.id)} />
            <Button
              key={`irrelevant-${i.id}`}
              label="Irrelevant"
              onPress={async () => {
                const args = ['used', '--irrelevant', i.id, ...(live.session ? ['--session', live.session.id] : [])]
                await rkb($, args, { cwd: live.session?.cwd })
                await drop(i.id)
              }}
            />
          </Box>
        ))}
        <Button key="dismiss" label="Dismiss" role="dismiss" onPress={() => update($, band, () => [])} />
      </Box>
    )
  })

  on('ui.render', { component: 'Pane', requestId: PANE }, async ($, e, next) => {
    if (e.surface === 'mobile') return next(e)
    const { Box, Button, Input, Markdown, Text } = $.ui.resolve(e)
    const width = Math.max(30, e.props.bodyColumns - 2)
    const v = await read($, view)
    const s = await read($, status)
    const tab = (to: View, label: string, hotkey: string) => (
      <Button key={`view-${to}`} label={label} hotkey={hotkey} variant={v === to ? 'primary' : undefined} onPress={() => show($, to)} />
    )
    const back = (to: View) => <Button key="back" label="Back" hotkey="b" onPress={() => update($, view, () => to)} />
    let body
    if (v === 'search') {
      const list = await read($, hits)
      const message = await read($, note)
      body = (
        <Box flexDirection="column" gap={1}>
          <Input
            key="query"
            placeholder="Search lessons, then press Enter"
            autoFocus
            onSubmit={async (query: string) => {
              const r = await rkb($, ['search', query], { cwd: live.session?.cwd })
              const found: Hit[] = (r.data?.results ?? []).map((h: Json) => ({
                id: h.id,
                title: h.title,
                relevance: h.relevance ?? null,
                kind: h.type ?? '',
                summary: h.summary ?? '',
              }))
              await update($, hits, () => found)
              await update($, note, () => (r.ok ? `${plural(found.length, 'result')} for "${query}"` : 'rkb search failed'))
            }}
          />
          {message !== '' && <Text dimColor>{message}</Text>}
          {list.length === 0 && message === '' && <Text dimColor>Search by symptom, error text or tool name.</Text>}
          {list.map(hit => (
            <Box key={`result-${hit.id}`} flexDirection="column">
              <Button key={`hit-${hit.id}`} plain label={cut(hit.title, width)} onPress={() => openLesson($, hit.id)} />
              <Box gap={1}>
                <Text color={TYPE_COLOR[hit.kind]}>{hit.kind}</Text>
                {hit.relevance && <Text color={relevanceColor(hit.relevance)}>{hit.relevance}</Text>}
                <Text dimColor>{hit.id}</Text>
              </Box>
              {hit.summary !== '' && (
                <Text dimColor wrap="truncate-end">
                  {hit.summary}
                </Text>
              )}
            </Box>
          ))}
        </Box>
      )
    } else if (v === 'lesson') {
      const l = await read($, lesson)
      body = l ? (
        <Box flexDirection="column" gap={1}>
          <Box flexDirection="column">
            <Text bold color="cyan">
              {l.title}
            </Text>
            <Text dimColor wrap="truncate-end">{l.meta}</Text>
            <Text dimColor>{RULE.repeat(width)}</Text>
          </Box>
          <Markdown key="lesson" text={l.body.replace(/^# .*\n+/, '')} />
          {back('search')}
        </Box>
      ) : (
        <Text dimColor>No lesson open.</Text>
      )
    } else if (v === 'item') {
      const i = await read($, item)
      body = i ? (
        <Box flexDirection="column" gap={1}>
          <Box flexDirection="column">
            <Text bold color="cyan" wrap="truncate-end">
              {i.title}
            </Text>
            <Text dimColor wrap="truncate-end">{i.meta}</Text>
            <Text dimColor>{RULE.repeat(width)}</Text>
          </Box>
          <Markdown key="item" text={i.body} />
          {back('inbox')}
        </Box>
      ) : (
        <Text dimColor>No item open.</Text>
      )
    } else if (v === 'inbox') {
      const rows = await read($, inbox)
      const room = Math.max(10, width - 18)
      body = (
        <Box flexDirection="column">
          {rows.length === 0 && <Text dimColor>The inbox is empty.</Text>}
          {rows.length > 0 && (
            <Box gap={2} marginBottom={1}>
              <Text>
                <Text color="red">{DOT_MARK}</Text> high
              </Text>
              <Text>
                <Text color="yellow">{DOT_MARK}</Text> med
              </Text>
              <Text dimColor>{DOT_MARK} low</Text>
            </Box>
          )}
          {rows.map(row => {
            const level = LEVEL[row.priority] ?? LEVEL[1]!
            return (
              <Box key={`item-${row.id}`} gap={1}>
                <Text color={level.color} dimColor={!level.color}>
                  {DOT_MARK}
                </Text>
                <Box width={8}>
                  <Text dimColor>{KIND[row.kind] ?? row.kind}</Text>
                </Box>
                <Box flexGrow={1}>
                  <Button key={`open-${row.id}`} plain label={cut(row.preview, room)} onPress={() => openItem($, row)} />
                </Box>
                <Text dimColor>{row.age}</Text>
              </Box>
            )
          })}
        </Box>
      )
    } else {
      const open = s?.requests ?? []
      body = (
        <Box flexDirection="column" gap={1}>
          {open.length === 0 && <Text dimColor>No open requests. A request that rkb or a background agent leaves open shows here.</Text>}
          {open.map(q => (
            <Box key={`request-${q.id}`} flexDirection="column" borderStyle="round" borderColor="yellow" paddingX={1}>
              <Text bold>{q.question}</Text>
              <Text dimColor>{q.options.join(' / ')}</Text>
              <Box gap={1}>
                <Button key={`answer-${q.id}`} label="Answer" variant="primary" onPress={() => (live.session ? answer($, live.session, q) : undefined)} />
                <Text dimColor>{q.id}</Text>
              </Box>
            </Box>
          ))}
        </Box>
      )
    }
    return (
      <Box flexDirection="column" paddingX={1}>
        <Box gap={1}>
          {tab('search', 'Search', 's')}
          {tab('inbox', `Inbox ${s?.inbox ?? 0}`, 'i')}
          {tab('requests', `Requests ${s?.requests.length ?? 0}`, 'r')}
        </Box>
        <Box marginBottom={1}>
          <Text dimColor>{RULE.repeat(width)}</Text>
        </Box>
        {body}
      </Box>
    )
  })
}
