// Generated by rkb install; changes are overwritten. Remove with: rkb install --uninstall claude
//
// Shows rkb's state in Claude Code and runs the observer inside the session. Every decision is
// made by the rkb binary; this module only calls it and draws what it prints.
import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { Hit, InboxRow, Injected, Item, Lesson, Notice, Request, Status, View } from '../types'

// The rkb binary that installed this file; rkb install fills it in.
const RKB: string = "__RKB__"
const PANE = 'rkb'
const COMMAND = 'rkb-status'
const DOT = ' \u00b7 '
const KIND: Record<string, string> = { transcript: 'extract', observed: 'observed', note: 'note' }
const ACCENT = 'cyan'
const BAR_FULL = '\u2588'
const BAR_EMPTY = '\u2591'
const TONE: Record<Notice['tone'], [string, string]> = { ok: ['\u2713', 'green'], fail: ['\u2717', 'red'], busy: ['\u2026', 'yellow'] }
const APPLIES_COLOR: Record<string, string> = { yes: 'green', likely: 'green', unlikely: 'yellow', no: 'red' }
const DOT_MARK = '\u25cf'
const ARROW = '\u203a'
const LEVEL: Record<number, { label: string; color?: string }> = {
  3: { label: 'high', color: 'red' },
  2: { label: 'med', color: 'yellow' },
  1: { label: 'low' },
}
const TYPE_COLOR: Record<string, string> = { pitfall: 'red', recipe: 'green', fact: 'cyan', decision: 'magenta', preference: 'yellow' }
// No closeOnEscape: Esc hands the keys back and the pane stays, as Claude Code's diff panel does; the dock
// keeps both as tabs.
// No columns: the dock opens it at its default share, as wide as Claude Code's diff panel.
const OPEN = { id: PANE, title: 'rkb', focus: true } as const

function relevanceColor(r: string | null): string | undefined {
  const n = r === null ? NaN : Number(r)
  if (n >= 0.8) return 'green'
  if (n >= 0.5) return 'yellow'
  return undefined
}
const UI_TIMEOUT_MS = 5000
// A job step parses notes and writes the inbox item, and a prepare reads the transcript.
const JOB_TIMEOUT_MS = 30000
// A tool runs a search or a write, which may load a model, so it gets longer than a hook.
const TOOL_TIMEOUT_MS = 60000
const NOTES_MAX_TOKENS = 4096

const status = atom({ plugin: 'rkb', key: 'status' } as const, null)
const band = atom({ plugin: 'rkb', key: 'band' } as const, [])
const seen = atom({ plugin: 'rkb', key: 'seen' } as const, [])
const view = atom({ plugin: 'rkb', key: 'view' } as const, 'search')
const hits = atom({ plugin: 'rkb', key: 'hits' } as const, [])
const lesson = atom({ plugin: 'rkb', key: 'lesson' } as const, null)
const item = atom({ plugin: 'rkb', key: 'item' } as const, null)
const inbox = atom({ plugin: 'rkb', key: 'inbox' } as const, [])
const note = atom({ plugin: 'rkb', key: 'note' } as const, '')
const notice = atom({ plugin: 'rkb', key: 'notice' } as const, null)

type Json = Record<string, any>
type Ran = { ok: boolean; data: Json | undefined }
type Session = { id: string; cwd: string; transcript?: string }

/** Runs rkb with JSON output; never throws. `ok` is false when rkb is missing, failed or printed no JSON. */
async function rkb($: EngineInterface, args: string[], opts: { cwd?: string; stdin?: string; timeoutMs?: number } = {}): Promise<Ran> {
  try {
    const r = await $.process.run([RKB, ...args, '--format', 'json'], {
      cwd: opts.cwd,
      stdin: opts.stdin,
      timeoutMs: opts.timeoutMs ?? UI_TIMEOUT_MS,
    })
    let data: Json | undefined
    try {
      data = JSON.parse(r.stdout)
    } catch {
      data = undefined
    }
    return { ok: r.exitCode === 0 && data !== undefined, data }
  } catch {
    return { ok: false, data: undefined }
  }
}

/** `text` on one line, cut to `width` characters with `...`. */
function cut(text: string, width: number): string {
  const line = text.replace(/\s+/g, ' ').trim()
  return line.length <= width ? line : `${line.slice(0, Math.max(0, width - 3))}...`
}

function plural(n: number, word: string): string {
  return `${n} ${word}${n === 1 ? '' : 's'}`
}

export function statusLine(s: Status | null): string | undefined {
  if (!s) return undefined
  const parts: string[] = []
  if (s.inbox > 0) parts.push(`${s.inbox} inbox (${s.high} high)`)
  if (s.curate > 0) parts.push(`${s.curate} curate`)
  if (s.requests.length > 0) parts.push(plural(s.requests.length, 'request'))
  return parts.length === 0 ? undefined : parts.join(DOT)
}

async function refresh($: EngineInterface, session: Session): Promise<void> {
  const r = await rkb($, ['status', '--session', session.id], { cwd: session.cwd })
  if (!r.ok || !r.data) return
  const d = r.data
  const s: Status = {
    inbox: d.inbox?.total ?? 0,
    high: d.inbox?.priority?.['3'] ?? 0,
    curate: d.curate ?? 0,
    requests: (d.requests ?? []).map((q: Json): Request => ({ id: q.id, question: q.question, options: q.options ?? [] })),
  }
  await update($, status, () => s)
  $.ui.status(statusLine(s))
  const injected: Injected[] = (d.injected ?? []).map((i: Json) => ({ id: i.id, title: i.title ?? null, hook: i.hook ?? null }))
  const known = await read($, seen)
  const fresh = injected.filter(i => !known.includes(i.id))
  if (fresh.length > 0) {
    await update($, seen, ids => [...ids, ...fresh.map(i => i.id)])
    await update($, band, shown => [...shown, ...fresh])
  }
}

/**
 * Runs one model job of any kind: rkb prepares each part, the session's own client answers it, and rkb
 * handles the answer. Returns the last thing rkb printed.
 */
async function runJob($: EngineInterface, session: Session, prepare: string[]): Promise<Json | undefined> {
  const model = await $.session.model()
  let step = (await rkb($, [...prepare, '--model', model], { cwd: session.cwd, timeoutMs: JOB_TIMEOUT_MS })).data
  while (step?.job && step.prompt) {
    const finish = ['job', 'finish', step.job, '--part', String(step.part)]
    const failures: string[] = []
    let next: Json | undefined
    let answered = false
    for (const m of step.models as { entry: string; model: string | null }[]) {
      const r = await $.model.complete({ model: m.model ?? model, prompt: step.prompt, maxTokens: NOTES_MAX_TOKENS })
      if (r.isAnswered) {
        next = (await rkb($, [...finish, '--model', m.entry], { cwd: session.cwd, stdin: r.text, timeoutMs: JOB_TIMEOUT_MS })).data
        answered = true
        break
      }
      failures.push(`${m.entry}: ${r.reason}`)
    }
    if (!answered) {
      await rkb($, [...finish, '--failed', failures.join('; ')], { cwd: session.cwd })
      return undefined
    }
    step = next
  }
  return step
}

/** One observer run, then triage of the inbox and the small model for what triage left unsure. */
async function observe($: EngineInterface, session: Session): Promise<void> {
  if (session.transcript) {
    const prepare = ['job', 'prepare', 'observe', '--session', session.id, '--transcript', session.transcript, '--harness', 'claude-code', '--cwd', session.cwd]
    const done = await runJob($, session, prepare)
    if (done?.outcome === 'added') $.ui.toast(`rkb: ${plural(done.notes, 'note')} for the inbox`)
  }
  await rkb($, ['inbox', 'triage'], { cwd: session.cwd, timeoutMs: JOB_TIMEOUT_MS })
  await runJob($, session, ['job', 'prepare', 'triage', '--harness', 'claude-code'])
}

async function say($: EngineInterface, tone: Notice['tone'], text: string): Promise<void> {
  await update($, notice, () => ({ tone, text }))
}

async function openLesson($: EngineInterface, id: string): Promise<void> {
  const r = await rkb($, ['show', id])
  if (!r.ok || !r.data) {
    await say($, 'fail', `Cannot show ${id}.`)
    return
  }
  const d = r.data
  const l: Lesson = {
    id,
    title: d.title ?? id,
    body: String(d.body ?? '').replace(/^# .*\n+/, ''),
    kind: d.frontmatter?.type ?? '',
    status: d.frontmatter?.status ?? '',
    path: d.path ?? '',
    applies: d.applies?.result ?? '',
  }
  await update($, lesson, () => l)
  await update($, notice, () => null)
  await update($, view, () => 'lesson' as View)
  await $.ui.open(OPEN)
}

async function openItem($: EngineInterface, row: InboxRow): Promise<void> {
  const r = await rkb($, ['inbox', 'show', row.id])
  if (!r.ok || !r.data) {
    await say($, 'fail', `Cannot show inbox item ${row.id}.`)
    return
  }
  const i: Item = { ...row, title: row.preview, body: r.data.body ?? '', cwd: r.data.meta?.cwd ?? '' }
  await update($, item, () => i)
  await update($, notice, () => null)
  await update($, view, () => 'item' as View)
}

async function show($: EngineInterface, v: View): Promise<void> {
  if (v === 'inbox') {
    const r = await rkb($, ['inbox'])
    const rows: InboxRow[] = (r.data?.items ?? []).map((i: Json) => ({
      id: i.id,
      kind: i.kind,
      priority: i.priority,
      age: i.age,
      preview: i.preview,
      verdicts: i.verdicts ?? null,
    }))
    await update($, inbox, () => rows)
  }
  await update($, notice, () => null)
  await update($, view, () => v)
  if (v === 'search') await $.ui.focus({ requestId: PANE, key: 'query' }).catch(() => undefined)
}

async function answer($: EngineInterface, session: Session, q: Request): Promise<void> {
  let choice: string
  try {
    choice = await $.ui.ask(q.question.endsWith('?') ? q.question : `${q.question}?`, { options: q.options.slice(0, 4), header: 'rkb' })
  } catch {
    return
  }
  await say($, 'busy', `Running rkb confirm ${q.id}...`)
  const r = await rkb($, ['confirm', q.id, '--choice', choice], { cwd: session.cwd })
  const d = r.data ?? {}
  await say($, r.ok ? 'ok' : 'fail', r.ok ? `${q.id}: ${choice}${d.id ? ` (${d.id})` : ''}` : (d.error?.message ?? 'rkb confirm failed'))
  await refresh($, session)
}

/** Records how a lesson opened in the pane did, as `rkb_used` does for the agent. */
async function used($: EngineInterface, session: Session | undefined, id: string, result: 'worked' | 'irrelevant'): Promise<void> {
  const r = await rkb($, ['used', `--${result}`, id, ...(session ? ['--session', session.id] : [])], { cwd: session?.cwd })
  await say($, r.ok ? 'ok' : 'fail', r.ok ? `Recorded ${id} as ${result}.` : (r.data?.error?.message ?? 'rkb used failed'))
}

/**
 * Queues one of the plugin's commands (`/rkb:distill` and so on) as if the person typed it. It runs as a
 * turn once the session is idle, so the button does not wait for it.
 */
async function runCommand($: EngineInterface, name: 'distill' | 'curate' | 'retro'): Promise<void> {
  await say($, 'busy', `Queued /rkb:${name}; it runs as a turn when the session is idle.`)
  void $.command.run({ command: `rkb:${name}` }).catch(() => say($, 'fail', `Claude Code did not run /rkb:${name}.`))
}

/** Runs triage on the inbox and redraws it with the verdicts; triage changes no lesson. */
async function triageNow($: EngineInterface, cwd: string | undefined): Promise<void> {
  await say($, 'busy', 'Triaging the inbox...')
  const r = await rkb($, ['inbox', 'triage'], { cwd, timeoutMs: JOB_TIMEOUT_MS })
  const t = r.data?.total
  const text = r.ok && t ? `Triaged: ${t.keep} keep, ${t.known} known, ${t.unsure} unsure, ${t.drop} drop` : 'rkb inbox triage failed'
  await show($, 'inbox')
  await say($, r.ok ? 'ok' : 'fail', text)
}

/** `2 keep · 1 drop` for a row's verdicts; nothing before triage. */
function verdictText(v: InboxRow['verdicts']): string {
  if (!v) return ''
  return (
    [
      [v.keep, 'keep'],
      [v.known, 'known'],
      [v.unsure, 'unsure'],
      [v.drop, 'drop'],
    ] as const
  )
    .filter(([n]) => n > 0)
    .map(([n, w]) => `${n} ${w}`)
    .join(DOT)
}

/** A 10-cell bar for a relevance from 0 to 1. */
function bar(relevance: number): string {
  const fill = Math.max(0, Math.min(10, Math.round(relevance * 10)))
  return BAR_FULL.repeat(fill) + BAR_EMPTY.repeat(10 - fill)
}

// `start` is the session context rkb prints at session start, delivered with the next prompt.
type Live = { session?: Session; isOff: boolean; isObserving: boolean; tools: Set<string>; start?: Promise<string> }
type AutoKind = 'distill' | 'curate'

const AUTO_TASK: Record<AutoKind, string> = {
  distill: 'Distill the triaged rkb inbox into lessons, as your steps say.',
  curate: 'Curate the rkb knowledge base, as your steps say.',
}

/**
 * Starts the agent for an automatic run when rkb says one is due and this session wins the claim. rkb
 * holds the gates (`[distill] auto`, the gap since the last run) and records the start in the claim.
 */
async function autoRun($: EngineInterface, session: Session, kind: AutoKind): Promise<boolean> {
  const claim = await rkb($, ['auto', 'claim', kind], { cwd: session.cwd })
  if (claim.data?.claimed !== true) return false
  const started = await $.agent
    .spawn({ subagentType: `rkb:${kind}`, description: `rkb ${kind}`, prompt: AUTO_TASK[kind] })
    .then(r => !r.deny)
    .catch(() => false)
  if (started) $.ui.toast(`rkb: ${kind} started in the background`)
  return started
}

// Claude Code lists a mod's tool as `mcp__<plugin>__<name>`, so `rkb_search` becomes `mcp__rkb__search`.
const TOOL_PREFIX = 'mcp__rkb__'
// The plugin's MCP server offers the same tools for sessions without the mod: `mcp__plugin_rkb_rkb__rkb_search`
// when installed, `mcp__rkb__rkb_search` from a plugin folder.
const MCP_COPY = /^mcp__.+__rkb_[a-z]+$/
// The tools settings.json allows without a prompt when they come from `rkb mcp`.
const ALLOWED = new Set(['search', 'show', 'add', 'note'].map(n => TOOL_PREFIX + n))

/** Registers the agent tools from `rkb tools` under short names into `tools`; registers none when rkb fails. */
async function registerTools($: EngineInterface, tools: Set<string>): Promise<void> {
  const r = await rkb($, ['tools'])
  for (const t of (r.data?.tools ?? []) as { name: string; description: string; inputSchema: Record<string, unknown> }[]) {
    const name = t.name.replace(/^rkb_/, '')
    const ok = await $.tool.register({ name, description: t.description, inputSchema: t.inputSchema }).then(
      () => true,
      () => false,
    )
    if (ok) tools.add(TOOL_PREFIX + name)
  }
}

/** The session context started at session start, or '' once `UI_TIMEOUT_MS` passed. */
async function startContext($: EngineInterface, live: Live): Promise<string> {
  const start = live.start
  live.start = undefined
  if (!start) return ''
  return Promise.race([start, $.clock.sleep(UI_TIMEOUT_MS).then(() => '')])
}

/** Runs `rkb tool rkb_<name>` for a call of `mcp__rkb__<name>`; a failure is a refusal the model reads as an error. */
async function callTool($: EngineInterface, cwd: string | undefined, tool: string, args: Record<string, unknown>) {
  const name = `rkb_${tool.slice(TOOL_PREFIX.length)}`
  try {
    const r = await $.process.run([RKB, 'tool', name], { cwd, stdin: JSON.stringify(args), timeoutMs: TOOL_TIMEOUT_MS })
    const text = r.stdout.trim()
    // Exit 3 is a question for the user, which the agent passes on; 1 and 2 are failures.
    if (r.exitCode === 1 || r.exitCode === 2) return { deny: text || `rkb exited with ${r.exitCode}` }
    return { result: text }
  } catch {
    return { deny: 'rkb did not run: check that the rkb command is installed (`rkb doctor` in a terminal).' }
  }
}
type Reply = { additionalContext?: string[]; block?: string }

/** Runs `rkb hook <event> --mod` with a classic hook's input; the reply text, or '' when rkb failed. */
async function hook($: EngineInterface, event: string, input: { cwd: string }): Promise<string> {
  try {
    const r = await $.process.run([RKB, 'hook', event, '--mod'], { cwd: input.cwd, stdin: JSON.stringify(input), timeoutMs: UI_TIMEOUT_MS })
    return r.exitCode === 0 ? r.stdout.trim() : ''
  } catch {
    return ''
  }
}

/** `result` with rkb's hook reply added: plain text or `additionalContext` as context, `decision: block` as `block`. */
export function withReply<R extends Reply>(result: R, out: string): R {
  if (out === '') return result
  let reply: Json | undefined
  try {
    reply = JSON.parse(out)
  } catch {
    reply = undefined
  }
  if (typeof reply !== 'object' || reply === null) return { ...result, additionalContext: [...(result.additionalContext ?? []), out] }
  const next: R = { ...result }
  const context = reply.hookSpecificOutput?.additionalContext
  if (typeof context === 'string' && context !== '') next.additionalContext = [...(result.additionalContext ?? []), context]
  if (reply.decision === 'block' && typeof reply.reason === 'string') next.block = reply.reason
  return next
}

/** Runs `work` after the current dispatch, so a turn or a compaction never waits for it. */
function later($: EngineInterface, work: () => Promise<void>): void {
  $.clock.after(0, () => {
    void work().catch(() => undefined)
  })
}

function turnEnded($: EngineInterface, live: Live, e: { session_id: string; cwd: string; transcript_path: string }): void {
  const s: Session = { id: e.session_id, cwd: e.cwd, transcript: e.transcript_path }
  live.session = s
  later($, async () => {
    await refresh($, s)
    if (live.isObserving) return
    live.isObserving = true
    try {
      await observe($, s)
      if (!(await autoRun($, s, 'distill'))) await autoRun($, s, 'curate')
    } finally {
      live.isObserving = false
    }
  })
}

export const register: Register = on => {
  const live: Live = { isOff: false, isObserving: false, tools: new Set() }

  on('session.start', async ($, e, next) => {
    live.isOff = Boolean(await $.env.get('RKB_OBSERVER'))
    if (!live.isOff) {
      const s: Session = { id: await $.session.id(), cwd: e.cwd }
      live.session = s
      // `/rkb` belongs to the plugin's skill, so Claude Code refuses it for a mod command.
      // Nothing here holds the first prompt: the command, the tools and the status come in the background.
      later($, async () => {
        await Promise.all([
          $.command.register({ name: COMMAND, description: 'Search lessons, read the inbox and answer rkb requests in a pane' }).catch(() => undefined),
          registerTools($, live.tools),
          refresh($, s),
        ])
      })
    }
    return next(e)
  })

  on('tool.call', async ($, e, next) => {
    if (!live.tools.has(e.tool)) return next(e)
    const { tool, tool_use_id: _id, ...args } = e as { tool: string; tool_use_id: string } & Record<string, unknown>
    return callTool($, live.session?.cwd, tool, args)
  })

  on('tool.check', async ($, e, next) => (ALLOWED.has(e.tool) ? { decision: 'allow' as const } : next(e)))

  // With the mod's tools registered, the MCP copies move behind ToolSearch: the model sees their names only.
  on('tool.describe', async ($, e, next) => {
    const r = await next(e)
    return live.tools.size > 0 && MCP_COPY.test(e.tool) ? { ...r, isDeferred: true } : r
  })

  // Every event but PreToolUse goes to `rkb hook --mod`; the plugin's command hooks of this session then do
  // nothing, because `RKB_MOD` names it. The confirm gate stays a command hook: only its input has
  // `permission_mode`.
  // The session context is built in the background and goes with the next prompt, the first time the
  // model runs, so a session never waits for rkb to start.
  on('classic.SessionStart', async ($, e, next) => {
    await $.env.set('RKB_MOD', e.session_id)
    let resolve: (text: string) => void = () => undefined
    live.start = new Promise(r => (resolve = r))
    later($, async () => resolve(await hook($, 'session-start', e)))
    return next(e)
  })

  on('classic.UserPromptSubmit', async ($, e, next) => {
    const r = withReply(await next(e), await startContext($, live))
    return withReply(r, await hook($, 'prompt', e))
  })

  on('classic.PostToolUse', async ($, e, next) => {
    const r = await next(e)
    return e.tool_name === 'Bash' ? withReply(r, await hook($, 'tool-ok', e)) : r
  })

  on('classic.PostToolUseFailure', async ($, e, next) => {
    const r = await next(e)
    return e.tool_name === 'Bash' ? withReply(r, await hook($, 'tool-failed', e)) : r
  })

  on('classic.Stop', async ($, e, next) => {
    const r = withReply(await next(e), await hook($, 'stop', e))
    if (!live.isOff) turnEnded($, live, e)
    return r
  })

  on('classic.PreCompact', async ($, e, next) => {
    await hook($, 'pre-compact', e)
    if (!live.isOff) turnEnded($, live, e)
    return next(e)
  })

  on('classic.SessionEnd', async ($, e, next) => {
    await hook($, 'session-end', e)
    return next(e)
  })

  on('prompt.submit', async ($, e, next) => {
    if (!live.isOff) await update($, band, () => [])
    return next(e)
  })

  on('command.run', { command: COMMAND }, async $ => {
    await $.ui.open(OPEN)
    return {}
  })

  on('ui.render', { component: 'AbovePrompt' }, async ($, e, next) => {
    const shown = await read($, band)
    if (shown.length === 0) return next(e)
    const { Box, Button, Text } = $.ui.resolve(e)
    const drop = (id: string) => update($, band, list => list.filter(i => i.id !== id))
    return (
      <Box flexDirection="column">
        {shown.map(i => (
          <Box key={`lesson-${i.id}`} gap={1}>
            <Text color="cyan">{ARROW} rkb</Text>
            <Text dimColor>{i.hook ?? 'hook'}</Text>
            <Text>{i.title ?? i.id}</Text>
            <Box flexShrink={0}>
                    <Text dimColor>{i.id}</Text>
                  </Box>
            <Button key={`open-${i.id}`} label="Open" onPress={() => openLesson($, i.id)} />
            <Button
              key={`irrelevant-${i.id}`}
              label="Irrelevant"
              onPress={async () => {
                const args = ['used', '--irrelevant', i.id, ...(live.session ? ['--session', live.session.id] : [])]
                await rkb($, args, { cwd: live.session?.cwd })
                await drop(i.id)
              }}
            />
          </Box>
        ))}
        <Button key="dismiss" label="Dismiss" role="dismiss" onPress={() => update($, band, () => [])} />
      </Box>
    )
  })

  on('ui.render', { component: 'Pane', requestId: PANE }, async ($, e, next) => {
    if (e.surface === 'mobile') return next(e)
    const { Box, Button, Input, Markdown, Text } = $.ui.resolve(e)
    const width = Math.max(30, e.props.bodyColumns - 2)
    const v = await read($, view)
    const s = await read($, status)
    const said = await read($, notice)
    const home = await $.env.get('HOME')
    const tilde = (path: string) => (home && path.startsWith(`${home}/`) ? `~${path.slice(home.length)}` : path)

    // Two Buttons with one hotkey clash, so only the first drawn takes it.
    const taken = new Set<string>()
    const hot = (k: string) => {
      if (taken.has(k)) return undefined
      taken.add(k)
      return k
    }
    const button = (key: string, label: string, hotkey: string | undefined, onPress: () => unknown, primary = false) => (
      <Button key={key} label={label} hotkey={hotkey} plain variant={primary ? 'primary' : 'secondary'} dimColor={!primary} onPress={() => void onPress()} />
    )
    const badge = (label: string, color?: string) => (
      <Text inverse bold color={color}>
        {` ${label.toUpperCase()} `}
      </Text>
    )
    const empty = (line: string, hint: string) => (
      <Box borderStyle="round" borderDimColor flexDirection="column" paddingX={1}>
        <Text>{line}</Text>
        <Text dimColor>{hint}</Text>
      </Box>
    )

    const header = (
      <Box justifyContent="space-between" paddingRight={3}>
        <Text bold color={ACCENT}>
          rkb
        </Text>
        {s && (
          <Text dimColor>
            {s.inbox} inbox{DOT}
            <Text color={s.high > 0 ? 'red' : undefined}>{s.high} high</Text>
            {DOT}
            {s.curate} curate
          </Text>
        )}
      </Box>
    )
    const tabs = (
      <Box gap={3} marginBottom={1}>
        {button('view-search', 'Search', hot('s'), () => show($, 'search'), v === 'search' || v === 'lesson')}
        {button('view-inbox', `Inbox ${s?.inbox ?? 0}`, hot('i'), () => show($, 'inbox'), v === 'inbox' || v === 'item')}
        {button('view-requests', `Requests ${s?.requests.length ?? 0}`, hot('r'), () => show($, 'requests'), v === 'requests')}
      </Box>
    )
    const noticeLine = said && (
      <Box key="notice" marginBottom={1}>
        <Text wrap="truncate-end">
          <Text color={TONE[said.tone][1]}>{TONE[said.tone][0]}</Text> {said.text}
        </Text>
      </Box>
    )

    let body
    if (v === 'search') {
      const list = await read($, hits)
      const message = await read($, note)
      body = (
        <Box flexDirection="column" gap={1}>
          <Input
            key="query"
            placeholder="Search lessons: an error, a symptom or a tool"
            autoFocus
            onSubmit={async (query: string) => {
              const r = await rkb($, ['search', query], { cwd: live.session?.cwd })
              const found: Hit[] = (r.data?.results ?? []).map((h: Json) => ({
                id: h.id,
                title: h.title,
                relevance: h.relevance ?? null,
                kind: h.type ?? '',
                summary: h.summary ?? '',
                applies: h.applies ?? '',
              }))
              await update($, hits, () => found)
              await update($, note, () => (r.ok ? `${plural(found.length, 'result')} for "${query}"` : 'rkb search failed'))
            }}
          />
          {message !== '' && <Text dimColor>{message}</Text>}
          {list.length === 0 && message === '' && empty('Search your lessons.', 'Paste an error message, or name a tool or a symptom.')}
          {list.map(hit => {
            const score = hit.relevance === null ? NaN : Number(hit.relevance)
            return (
              <Box key={`result-${hit.id}`} borderStyle="round" borderColor={TYPE_COLOR[hit.kind]} borderDimColor flexDirection="column" paddingX={1}>
                <Box justifyContent="space-between" gap={1}>
                  <Text wrap="truncate-end">
                    {badge(hit.kind, TYPE_COLOR[hit.kind])} <Text bold>{hit.title}</Text>
                  </Text>
                  <Box flexShrink={0}>
                    <Text dimColor>{hit.id}</Text>
                  </Box>
                </Box>
                <Text wrap="truncate-end">
                  {Number.isFinite(score) && (
                    <Text color={relevanceColor(hit.relevance)} dimColor={!relevanceColor(hit.relevance)}>
                      {`${bar(score)} ${score.toFixed(2)}`}
                    </Text>
                  )}
                  {Number.isFinite(score) && DOT}
                  <Text dimColor>applies </Text>
                  <Text color={APPLIES_COLOR[hit.applies]} dimColor={!APPLIES_COLOR[hit.applies]}>
                    {hit.applies || 'unknown'}
                  </Text>
                </Text>
                {hit.summary !== '' && (
                  <Text dimColor wrap="truncate-end">
                    {hit.summary}
                  </Text>
                )}
                {button(`hit-${hit.id}`, 'Open', hot('o'), () => openLesson($, hit.id), true)}
              </Box>
            )
          })}
        </Box>
      )
    } else if (v === 'lesson') {
      const l = await read($, lesson)
      body = l ? (
        <Box borderStyle="round" borderColor={ACCENT} flexDirection="column" paddingX={1}>
          <Box justifyContent="space-between" gap={1}>
            <Text wrap="truncate-end">
              {badge(l.kind || 'lesson', TYPE_COLOR[l.kind])} <Text bold>{l.title}</Text>
            </Text>
            <Box flexShrink={0}>
                    <Text dimColor>{l.id}</Text>
                  </Box>
          </Box>
          <Text dimColor wrap="truncate-end">
            {[l.status, l.applies ? `applies ${l.applies}` : '', l.path].filter(Boolean).join(DOT)}
          </Text>
          <Box marginTop={1}>
            <Markdown key="lesson" text={l.body} />
          </Box>
          <Box gap={3} marginTop={1}>
            {button('worked', 'Worked', hot('w'), () => used($, live.session, l.id, 'worked'), true)}
            {button('irrelevant', 'Irrelevant', hot('x'), () => used($, live.session, l.id, 'irrelevant'))}
            {button('back', 'Back', hot('b'), () => update($, view, () => 'search' as View))}
          </Box>
        </Box>
      ) : (
        empty('No lesson open.', 'Open one from a search.')
      )
    } else if (v === 'item') {
      const i = await read($, item)
      const level = LEVEL[i?.priority ?? 1] ?? LEVEL[1]!
      body = i ? (
        <Box borderStyle="round" borderColor={level.color ?? ACCENT} flexDirection="column" paddingX={1}>
          <Box justifyContent="space-between" gap={1}>
            <Text wrap="truncate-end">
              {badge(KIND[i.kind] ?? i.kind, level.color)} <Text bold>{i.title}</Text>
            </Text>
            <Text dimColor>{i.id}</Text>
          </Box>
          <Text dimColor wrap="truncate-end">
            {[`${level.label} priority`, i.age, tilde(i.cwd)].filter(Boolean).join(DOT)}
          </Text>
          <Box marginTop={1}>
            <Markdown key="item" text={i.body} />
          </Box>
          <Box gap={3} marginTop={1}>
            {button('back', 'Back', hot('b'), () => update($, view, () => 'inbox' as View))}
          </Box>
        </Box>
      ) : (
        empty('No inbox item open.', 'Open one from the inbox.')
      )
    } else if (v === 'inbox') {
      const rows = await read($, inbox)
      const room = Math.max(10, width - 34)
      const actions = (
        <Box key="actions" gap={3} marginBottom={1}>
          {button('triage', 'Triage', hot('g'), () => triageNow($, live.session?.cwd), rows.some(row => !row.verdicts))}
          {button('distill', 'Distill', hot('d'), () => runCommand($, 'distill'), rows.length > 0)}
          {button('curate', `Curate ${s?.curate ?? 0}`, hot('c'), () => runCommand($, 'curate'), (s?.curate ?? 0) > 0)}
          {button('retro', 'Retro', hot('t'), () => runCommand($, 'retro'))}
        </Box>
      )
      const list =
        rows.length === 0 ? (
          empty('The inbox is empty.', 'Notes and session extracts wait here until distill turns them into lessons.')
        ) : (
          <Box flexDirection="column" gap={1}>
            {[3, 2, 1].map(p => {
              const group = rows.filter(row => row.priority === p)
              const level = LEVEL[p]!
              if (group.length === 0) return null
              return (
                <Box key={`group-${p}`} flexDirection="column">
                  <Text bold color={level.color} dimColor={!level.color}>
                    {DOT_MARK} {level.label} <Text dimColor>{group.length}</Text>
                  </Text>
                  {group.map(row => (
                    <Box key={`item-${row.id}`} justifyContent="space-between" gap={1}>
                      <Box gap={1}>
                        <Box width={8}>
                          <Text dimColor>{KIND[row.kind] ?? row.kind}</Text>
                        </Box>
                        {button(`open-${row.id}`, cut(row.preview, room), undefined, () => openItem($, row))}
                      </Box>
                      <Text dimColor>
                        {[verdictText(row.verdicts), row.age].filter(Boolean).join(DOT)}
                      </Text>
                    </Box>
                  ))}
                </Box>
              )
            })}
          </Box>
        )
      body = (
        <Box flexDirection="column">
          {actions}
          {list}
        </Box>
      )
    } else {
      const open = s?.requests ?? []
      body =
        open.length === 0 ? (
          empty('No open requests.', 'A question rkb or a background agent leaves for you shows here.')
        ) : (
          <Box flexDirection="column" gap={1}>
            {open.map(q => (
              <Box key={`request-${q.id}`} borderStyle="round" borderColor="yellow" flexDirection="column" paddingX={1}>
                <Box justifyContent="space-between" gap={1}>
                  <Text bold color="yellow">
                    needs you
                  </Text>
                  <Box flexShrink={0}>
                    <Text dimColor>{q.id}</Text>
                  </Box>
                </Box>
                <Text>{q.question}</Text>
                <Text dimColor wrap="truncate-end">
                  {q.options.join(' / ')}
                </Text>
                <Box marginTop={1}>
                  {button(`answer-${q.id}`, 'Answer', hot('a'), () => (live.session ? answer($, live.session, q) : undefined), true)}
                </Box>
              </Box>
            ))}
          </Box>
        )
    }
    return (
      <Box flexDirection="column" paddingX={1}>
        {header}
        {tabs}
        {noticeLine}
        {body}
      </Box>
    )
  })
}
