// Generated by rkb install; changes are overwritten. Remove with: rkb install --uninstall __HARNESS__
//
// Forwards __HARNESS__ events to `rkb hook <event>` as Claude Code shaped payloads and turns the
// replies back into results. All rkb logic lives in the rkb binary; this file only maps.
import { spawn } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

// rkb install fills in the harness, the binary, the prompts and the tool definitions.
const HARNESS: string = "__HARNESS__";
// The rkb binary that installed this file; rkb install fills it in.
const RKB: string = "__RKB__";
const TIMEOUT_MS = 5000;
// Kept here as well so a command that runs `rkb confirm` is gated even when `rkb` cannot run.
const CONFIRM = /(^|[\s;&|('"/])rkb\s+confirm\b/;
const NO_UI = "rkb confirm needs the user: ask them to run this command in their own terminal.";
const DECLINED = "The user declined this rkb confirm.";
// omp stops a session_shutdown handler after 2 s.
const SHUTDOWN_TIMEOUT_MS = 1800;
const RETRO: string = "__RETRO__";
const DISTILL: string = "__DISTILL__";
const CURATE: string = "__CURATE__";
const TOOLS_JSON: string = "__TOOLS__";
// A tool runs a search or a write, which may load a model, so it gets longer than a hook.
const TOOL_TIMEOUT_MS = 60000;

interface ToolDef {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}
const TOOLS: ToolDef[] = TOOLS_JSON.startsWith("[") ? JSON.parse(TOOLS_JSON) : [];

process.env.RKB_HARNESS = HARNESS;

interface Ran {
  code: number | null;
  out: string;
}

/** Runs rkb with `input` on stdin; undefined when it cannot start or takes longer than `timeoutMs`. */
function runRkb(args: string[], input: string, timeoutMs: number): Promise<Ran | undefined> {
  return new Promise((resolve) => {
    let out = "";
    let done = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const finish = (value?: Ran) => {
      if (done) return;
      done = true;
      if (timer) clearTimeout(timer);
      resolve(value);
    };
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn(RKB, args, { stdio: ["pipe", "pipe", "ignore"] });
    } catch {
      return finish();
    }
    timer = setTimeout(() => {
      child.kill("SIGKILL");
      finish();
    }, timeoutMs);
    child.on("error", () => finish());
    child.stdout?.on("data", (d: Buffer) => {
      out += d.toString();
    });
    child.on("close", (code: number | null) => finish({ code, out }));
    child.stdin?.on("error", () => {});
    child.stdin?.end(input);
  });
}

async function hook(event: string, payload: Record<string, unknown>, timeoutMs = TIMEOUT_MS): Promise<string | undefined> {
  const r = await runRkb(["hook", event, "--harness", HARNESS], JSON.stringify(payload), timeoutMs);
  return r && r.code === 0 && r.out.trim() ? r.out.trim() : undefined;
}

function parse(reply: string | undefined): any {
  if (!reply) return undefined;
  try {
    return JSON.parse(reply);
  } catch {
    return undefined;
  }
}

function additional(reply: string | undefined): string | undefined {
  const text = parse(reply)?.hookSpecificOutput?.additionalContext;
  return typeof text === "string" && text ? text : undefined;
}

// omp gives the session file and id in its stop event; kept for the compaction and shutdown hooks.
let stopSession: { id?: string; file?: string } = {};

function base(ctx: any): Record<string, unknown> {
  let session = "";
  try {
    session = String(ctx?.sessionManager?.getSessionId?.() ?? "");
  } catch {}
  return { session_id: session || stopSession.id || "", cwd: String(ctx?.cwd ?? process.cwd()) };
}

function transcript(ctx: any): string | undefined {
  let id = "";
  try {
    const file = ctx?.sessionManager?.getSessionFile?.();
    if (typeof file === "string" && file) return file;
    id = String(ctx?.sessionManager?.getSessionId?.() ?? "");
  } catch {}
  // Only this session's own file: an ephemeral session must not pick up an earlier session's transcript.
  return stopSession.file && (!id || id === stopSession.id) ? stopSession.file : undefined;
}

function prompt(text: string, args: string): string {
  return text.replace("$ARGUMENTS", args.trim() || "none");
}

function bash(event: any): string | undefined {
  return event?.toolName === "bash" ? String(event?.input?.command ?? "") : undefined;
}

// Claude Code's `error` starts with `Exit code N`; pi and omp end the output with `Command exited with code N`.
function errorText(content: any): string {
  const text = (Array.isArray(content) ? content : [])
    .filter((p: any) => p?.type === "text" && typeof p.text === "string")
    .map((p: any) => p.text)
    .join("\n")
    .replace(/\s+$/, "");
  const lines = text.split("\n");
  const m = /^Command exited with code (\d+)$/.exec((lines[lines.length - 1] ?? "").trim());
  if (!m) return text;
  lines.pop();
  return `Exit code ${m[1]}\n${lines.join("\n").replace(/\s+$/, "")}`;
}

function safe(fn: (event: any, ctx: any) => Promise<any>) {
  return async (event: any, ctx: any) => {
    try {
      return await fn(event, ctx);
    } catch {
      return undefined;
    }
  };
}

export default function rkb(pi: ExtensionAPI) {
  let startContext: string | undefined;
  // Lessons recalled for the user's message, added to the context of that turn.
  let recallContext: string | undefined;

  for (const tool of TOOLS) {
    pi.registerTool({
      name: tool.name,
      label: tool.name,
      description: tool.description,
      promptSnippet: tool.description.split(". ")[0],
      parameters: Type.Unsafe(tool.inputSchema),
      async execute(_id: string, params: unknown) {
        const r = await runRkb(["tool", tool.name], JSON.stringify(params ?? {}), TOOL_TIMEOUT_MS);
        if (!r) throw new Error("rkb did not run: check that the rkb command is installed (`rkb doctor` in a terminal).");
        const text = r.out.trim();
        // Exit 3 is a question for the user, which the agent passes on; 1 and 2 are failures.
        if (r.code === 1 || r.code === 2) throw new Error(text || `rkb exited with ${r.code}`);
        return { content: [{ type: "text", text }], details: {} };
      },
    });
  }
  // pi has no stop_hook_active flag, so the extension tracks its own continuation.
  let continuedByRkb = false;

  pi.on(
    "session_start",
    safe(async (event, ctx) => {
      startContext = await hook("session-start", { ...base(ctx), source: String(event?.reason ?? "startup") });
    }),
  );

  pi.on(
    "before_agent_start",
    safe(async () => {
      const parts = [startContext, recallContext].filter((p): p is string => Boolean(p));
      startContext = undefined;
      recallContext = undefined;
      if (parts.length === 0) return undefined;
      return { message: { customType: "rkb", content: parts.join("\n\n"), display: false } };
    }),
  );

  pi.on("tool_call", async (event: any, ctx: any) => {
    const command = bash(event);
    if (command === undefined || !command.includes("rkb")) return undefined;
    const gated = CONFIRM.test(command);
    try {
      const out = parse(await hook("pre-tool", { ...base(ctx), tool_name: "Bash", tool_input: { command } }))?.hookSpecificOutput;
      let reason: string;
      if (out?.permissionDecision === "ask") reason = String(out.permissionDecisionReason ?? "rkb confirm needs your approval");
      else if (gated) reason = "rkb confirm needs your approval";
      else return undefined;
      if (!ctx?.hasUI) return { block: true, reason: NO_UI };
      const yes = await ctx.ui.confirm("rkb confirm", `${reason}\n\nCommand: ${command}`);
      return yes ? undefined : { block: true, reason: DECLINED };
    } catch {
      return gated ? { block: true, reason: NO_UI } : undefined;
    }
  });

  pi.on(
    "tool_result",
    safe(async (event, ctx) => {
      const command = bash(event);
      if (command === undefined) return undefined;
      const payload = { ...base(ctx), tool_name: "Bash", tool_input: { command } };
      if (!event.isError) {
        await hook("tool-ok", payload);
        return undefined;
      }
      const note = additional(await hook("tool-failed", { ...payload, error: errorText(event.content) }));
      if (!note) return undefined;
      return { content: [...(Array.isArray(event.content) ? event.content : []), { type: "text", text: note }] };
    }),
  );

  pi.on(
    "session_before_compact",
    safe(async (_event, ctx) => {
      const path = transcript(ctx);
      if (path) await hook("pre-compact", { ...base(ctx), transcript_path: path });
      return undefined;
    }),
  );

  pi.on(
    "session_shutdown",
    safe(async (event, ctx) => {
      const path = transcript(ctx);
      if (path) await hook("session-end", { ...base(ctx), transcript_path: path, reason: String(event?.reason ?? "") }, SHUTDOWN_TIMEOUT_MS);
      return undefined;
    }),
  );

  for (const [name, text, description] of [
    ["rkb-retro", RETRO, "Record the durable lessons of this session in rkb now"],
    ["rkb-distill", DISTILL, "Turn a few rkb inbox items into lessons"],
    ["rkb-curate", CURATE, "Merge near-duplicate lessons, sharpen weak ones and archive ones that do not help"],
  ]) {
    pi.registerCommand(name, {
      description,
      handler: async (args: string) => {
        pi.sendUserMessage(prompt(text, String(args ?? "")));
      },
    });
  }

  pi.on(
    "input",
    safe(async (event, ctx) => {
      continuedByRkb = false;
      recallContext = additional(await hook("prompt", { ...base(ctx), prompt: String(event?.text ?? "") }));
      return HARNESS === "pi" ? { action: "continue" } : undefined;
    }),
  );

  if (HARNESS === "pi") {
    pi.on(
      "agent_before_settle",
      safe(async (event, ctx) => {
        if (event?.outcome !== "completed" || event?.context?.canContinue === false) return undefined;
        const note = additional(await hook("stop", { ...base(ctx), stop_hook_active: continuedByRkb }));
        if (!note) {
          continuedByRkb = false;
          return undefined;
        }
        continuedByRkb = true;
        const entries = Array.isArray(event.entries) ? event.entries : [];
        return { entries: [...entries, { type: "custom_message", customType: "rkb", content: note, display: false }], continue: true };
      }),
    );
  }

  if (HARNESS === "omp") {
    // omp's own event, which pi's types do not declare.
    const omp = pi as unknown as { on(event: "session_stop", handler: (event: any, ctx: any) => Promise<unknown>): void };
    omp.on(
      "session_stop",
      safe(async (event, ctx) => {
        if (event?.signal?.aborted) return undefined;
        if (event?.session_file) stopSession.file = String(event.session_file);
        if (event?.session_id) stopSession.id = String(event.session_id);
        const payload: Record<string, unknown> = { ...base(ctx), stop_hook_active: Boolean(event?.stop_hook_active) };
        if (event?.session_id) payload.session_id = String(event.session_id);
        const note = additional(await hook("stop", payload));
        return note ? { continue: true, additionalContext: note } : undefined;
      }),
    );
  }
}
