use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result, io};

/// The rkb skill, built into the binary so an installed copy always matches it.
pub const SKILL: &str = include_str!("../../../skills/rkb/SKILL.md");
/// The `/rkb-retro` and `/rkb-distill` command prompts: file name and text with frontmatter.
pub const COMMANDS: [(&str, &str); 2] = [
    ("rkb-retro.md", include_str!("../../../skills/rkb/commands/rkb-retro.md")),
    ("rkb-distill.md", include_str!("../../../skills/rkb/commands/rkb-distill.md")),
];
/// The line in every command file rkb writes; uninstall removes only files that have it.
const COMMAND_MARKER: &str = "\ngenerated-by: rkb install";

/// A command prompt without its frontmatter, as a harness sends it to the model.
pub fn command_body(text: &str) -> &str {
    text.strip_prefix("---\n").and_then(|t| t.split_once("\n---\n")).map_or(text, |(_, body)| body.trim_start())
}

/// The Claude Code permission rule that asks the user before `rkb confirm`.
pub const ASK_RULE: &str = "Bash(rkb confirm:*)";

/// The harness name `trust.toml` and `request::trusted_harness` use for Claude Code.
pub const CLAUDE_TRUST: &str = "claude-code";

/// The pi and omp extension, with `__HARNESS__` where the harness name goes.
const EXTENSION: &str = include_str!("../../../extensions/rkb.ts");
/// The first line of every extension file rkb writes; uninstall removes only files that start with it.
const EXTENSION_MARKER: &str = "// Generated by rkb install;";

/// The Claude Code hook events rkb adds: event, tool matcher, and the `rkb hook` event it runs.
pub const CLAUDE_HOOKS: [(&str, Option<&str>, &str); 8] = [
    ("SessionStart", None, "session-start"),
    ("PreToolUse", Some("Bash"), "pre-tool"),
    ("PostToolUse", Some("Bash"), "tool-ok"),
    ("PostToolUseFailure", Some("Bash"), "tool-failed"),
    ("UserPromptSubmit", None, "prompt"),
    ("Stop", None, "stop"),
    ("PreCompact", None, "pre-compact"),
    ("SessionEnd", None, "session-end"),
];

/// The command of one of rkb's hook entries: `rkb hook <event>`, or a path to a binary whose name
/// starts with `rkb`, then ` hook ` and one of rkb's events.
static HOOK_COMMAND: std::sync::LazyLock<regex::Regex> = std::sync::LazyLock::new(|| {
    let events: Vec<&str> = CLAUDE_HOOKS.iter().map(|h| h.2).collect();
    regex::Regex::new(&format!(r"^(?:\S*/)?rkb[^/\s]* hook (?:{})$", events.join("|"))).unwrap()
});

/// What hooks and the extension run: `rkb` when that name on `PATH` is this binary, which survives a
/// reinstall to the same place; otherwise this binary's absolute path, so they never run another rkb.
pub fn hook_binary() -> String {
    hook_binary_with(std::env::var_os("PATH").as_deref(), std::env::current_exe().ok().as_deref())
}

fn hook_binary_with(path: Option<&std::ffi::OsStr>, exe: Option<&Path>) -> String {
    let Some(exe) = exe else { return "rkb".into() };
    let exe = exe.canonicalize().unwrap_or_else(|_| exe.to_path_buf());
    let on_path = path.and_then(|p| std::env::split_paths(p).map(|d| d.join("rkb")).find(|f| f.is_file()));
    match on_path.and_then(|f| f.canonicalize().ok()) {
        Some(found) if found == exe => "rkb".into(),
        _ => exe.display().to_string(),
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Harness {
    Claude,
    Pi,
    Omp,
}

impl Harness {
    pub const ALL: [Harness; 3] = [Harness::Claude, Harness::Pi, Harness::Omp];

    pub fn name(self) -> &'static str {
        match self {
            Harness::Claude => "claude",
            Harness::Pi => "pi",
            Harness::Omp => "omp",
        }
    }

    pub fn parse(name: &str) -> Option<Self> {
        Self::ALL.into_iter().find(|h| h.name() == name)
    }

    /// The harness's own folder; the harness counts as detected when it exists.
    pub fn home(self, home: &Path) -> PathBuf {
        match self {
            Harness::Claude => home.join(".claude"),
            Harness::Pi => home.join(".pi"),
            Harness::Omp => home.join(".omp"),
        }
    }

    pub fn skill_dir(self, home: &Path) -> PathBuf {
        match self {
            Harness::Claude => home.join(".claude/skills/rkb"),
            Harness::Pi => home.join(".pi/agent/skills/rkb"),
            Harness::Omp => home.join(".omp/agent/skills/rkb"),
        }
    }

    pub fn detected(self, home: &Path) -> bool {
        self.home(home).is_dir()
    }

    /// The name `trust.toml`, `RKB_HARNESS` and `rkb hook --harness` use.
    pub fn trust_name(self) -> &'static str {
        match self {
            Harness::Claude => CLAUDE_TRUST,
            Harness::Pi => "pi",
            Harness::Omp => "omp",
        }
    }

    /// The rkb extension file, for harnesses that load TypeScript extensions.
    pub fn extension_file(self, home: &Path) -> Option<PathBuf> {
        match self {
            Harness::Claude => None,
            Harness::Pi => Some(home.join(".pi/agent/extensions/rkb.ts")),
            Harness::Omp => Some(home.join(".omp/agent/extensions/rkb.ts")),
        }
    }

    /// The extension text for this harness.
    pub fn extension(self) -> String {
        let json = |t: &str| serde_json::to_string(command_body(t)).expect("a string serializes");
        EXTENSION
            .replace("__HARNESS__", self.trust_name())
            .replace("\"__RETRO__\"", &json(COMMANDS[0].1))
            .replace("\"__DISTILL__\"", &json(COMMANDS[1].1))
            .replace("\"__RKB__\"", &serde_json::to_string(&hook_binary()).expect("a string serializes"))
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Step {
    WriteSkill { dir: PathBuf },
    RemoveSkill { dir: PathBuf },
    AddAskRule { settings: PathBuf },
    RemoveAskRule { settings: PathBuf },
    AddHooks { settings: PathBuf, bin: String },
    RemoveHooks { settings: PathBuf },
    WriteExtension { file: PathBuf, text: String },
    RemoveExtension { file: PathBuf },
    WriteCommand { file: PathBuf, text: &'static str },
    RemoveCommand { file: PathBuf },
    Trust { file: PathBuf, name: &'static str },
    Untrust { file: PathBuf, name: &'static str },
}

impl Step {
    /// The file this step writes or removes.
    pub fn file(&self) -> PathBuf {
        match self {
            Step::WriteSkill { dir } | Step::RemoveSkill { dir } => dir.join("SKILL.md"),
            Step::AddAskRule { settings }
            | Step::RemoveAskRule { settings }
            | Step::AddHooks { settings, .. }
            | Step::RemoveHooks { settings } => settings.clone(),
            Step::WriteExtension { file, .. } | Step::RemoveExtension { file } => file.clone(),
            Step::WriteCommand { file, .. } | Step::RemoveCommand { file } => file.clone(),
            Step::Trust { file, .. } | Step::Untrust { file, .. } => file.clone(),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Effect {
    Written,
    Unchanged,
    Removed,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Change {
    pub path: PathBuf,
    pub effect: Effect,
}

/// The steps for `harnesses`. Reads nothing and writes nothing.
pub fn plan(home: &Path, config_dir: &Path, harnesses: &[Harness], uninstall: bool) -> Vec<Step> {
    let mut steps = vec![];
    for h in harnesses {
        let dir = h.skill_dir(home);
        steps.push(if uninstall { Step::RemoveSkill { dir } } else { Step::WriteSkill { dir } });
        if *h == Harness::Claude {
            let settings = home.join(".claude/settings.json");
            if uninstall {
                steps.push(Step::RemoveAskRule { settings: settings.clone() });
                steps.push(Step::RemoveHooks { settings });
            } else {
                steps.push(Step::AddAskRule { settings: settings.clone() });
                steps.push(Step::AddHooks { settings, bin: hook_binary() });
            }
            for (name, text) in COMMANDS {
                let file = home.join(".claude/commands").join(name);
                steps.push(if uninstall { Step::RemoveCommand { file } } else { Step::WriteCommand { file, text } });
            }
        }
        if let Some(file) = h.extension_file(home) {
            steps.push(if uninstall { Step::RemoveExtension { file } } else { Step::WriteExtension { file, text: h.extension() } });
        }
        let (file, name) = (config_dir.join("trust.toml"), h.trust_name());
        steps.push(if uninstall { Step::Untrust { file, name } } else { Step::Trust { file, name } });
    }
    steps
}

fn write_atomic(path: &Path, text: &str) -> Result<()> {
    let dir = path.parent().expect("absolute path");
    std::fs::create_dir_all(dir).map_err(io(dir))?;
    let tmp = dir.join(format!(".{}.rkb-tmp", path.file_name().unwrap().to_string_lossy()));
    std::fs::write(&tmp, text).map_err(io(&tmp))?;
    std::fs::rename(&tmp, path).map_err(io(path))
}

fn read_settings(path: &Path) -> Result<serde_json::Value> {
    match std::fs::read_to_string(path) {
        Err(_) => Ok(serde_json::json!({})),
        Ok(t) if t.trim().is_empty() => Ok(serde_json::json!({})),
        Ok(t) => serde_json::from_str(&t).map_err(|e| Error::Refused(format!("{} is not valid JSON: {e}", path.display()))),
    }
}

fn write_settings(path: &Path, v: &serde_json::Value) -> Result<()> {
    let text = serde_json::to_string_pretty(v).expect("json serializes") + "\n";
    write_atomic(path, &text)
}

/// Adds or removes the ask rule. Returns whether the file changed.
fn ask_rule(path: &Path, add: bool) -> Result<bool> {
    let mut v = read_settings(path)?;
    if !v.is_object() {
        return Err(Error::Refused(format!("{} is not a JSON object", path.display())));
    }
    let has = v["permissions"]["ask"].as_array().is_some_and(|a| a.iter().any(|r| r == ASK_RULE));
    if add == has {
        return Ok(false);
    }
    if add {
        let perms = v.as_object_mut().unwrap().entry("permissions").or_insert_with(|| serde_json::json!({}));
        let ask = perms
            .as_object_mut()
            .ok_or_else(|| Error::Refused(format!("`permissions` in {} is not an object", path.display())))?
            .entry("ask")
            .or_insert_with(|| serde_json::json!([]));
        ask.as_array_mut()
            .ok_or_else(|| Error::Refused(format!("`permissions.ask` in {} is not a list", path.display())))?
            .push(ASK_RULE.into());
    } else if let Some(ask) = v["permissions"]["ask"].as_array_mut() {
        ask.retain(|r| r != ASK_RULE);
        // Leave no empty list or block behind that only rkb's rule needed.
        if ask.is_empty()
            && let Some(perms) = v["permissions"].as_object_mut()
        {
            perms.remove("ask");
            if perms.is_empty() {
                v.as_object_mut().unwrap().remove("permissions");
            }
        }
    }
    write_settings(path, &v)?;
    Ok(true)
}

fn is_rkb_command(c: &serde_json::Value) -> bool {
    c.as_str().is_some_and(|c| HOOK_COMMAND.is_match(c))
}

fn is_rkb_entry(entry: &serde_json::Value) -> bool {
    entry["hooks"].as_array().is_some_and(|hs| hs.iter().any(|h| is_rkb_command(&h["command"])))
}

/// With `Some(bin)`, adds rkb's entries under `hooks` running `bin`, and points existing ones at `bin`;
/// with `None`, removes them. Keeps the user's own. Returns whether the file changed.
fn hooks(path: &Path, bin: Option<&str>) -> Result<bool> {
    let mut v = read_settings(path)?;
    let not_object = |what: &str| Error::Refused(format!("`{what}` in {} is not an object", path.display()));
    let root = v.as_object_mut().ok_or_else(|| not_object("the file"))?;
    let mut changed = false;
    if let Some(bin) = bin {
        let block = root.entry("hooks").or_insert_with(|| serde_json::json!({})).as_object_mut().ok_or_else(|| not_object("hooks"))?;
        for (event, matcher, name) in CLAUDE_HOOKS {
            let command = format!("{bin} hook {name}");
            let list = block
                .entry(event)
                .or_insert_with(|| serde_json::json!([]))
                .as_array_mut()
                .ok_or_else(|| Error::Refused(format!("`hooks.{event}` in {} is not a list", path.display())))?;
            let suffix = format!(" hook {name}");
            let mut found = false;
            for h in list.iter_mut().filter_map(|e| e["hooks"].as_array_mut()).flatten() {
                if is_rkb_command(&h["command"]) && h["command"].as_str().is_some_and(|c| c.ends_with(&suffix)) {
                    found = true;
                    if h["command"] != command.as_str() {
                        h["command"] = command.clone().into();
                        changed = true;
                    }
                }
            }
            if found {
                continue;
            }
            let mut entry = serde_json::json!({ "hooks": [{ "type": "command", "command": command, "timeout": 5 }] });
            if let Some(m) = matcher {
                entry = serde_json::json!({ "matcher": m, "hooks": entry["hooks"] });
            }
            list.push(entry);
            changed = true;
        }
    } else if let Some(block) = root.get_mut("hooks").and_then(|h| h.as_object_mut()) {
        for list in block.values_mut() {
            if let Some(list) = list.as_array_mut() {
                let before = list.len();
                list.retain(|e| !is_rkb_entry(e));
                changed |= list.len() != before;
            }
        }
        if changed {
            block.retain(|_, list| list.as_array().is_none_or(|l| !l.is_empty()));
            if block.is_empty() {
                root.remove("hooks");
            }
        }
    }
    if changed {
        write_settings(path, &v)?;
    }
    Ok(changed)
}

/// Whether `settings.json` has any of rkb's hook entries.
pub fn hooks_installed(home: &Path) -> bool {
    let Ok(v) = read_settings(&home.join(".claude/settings.json")) else { return false };
    v["hooks"].as_object().is_some_and(|b| b.values().filter_map(|l| l.as_array()).flatten().any(is_rkb_entry))
}

/// Sets or removes `[harness.<name>] gated = true`. Returns whether the file changed.
fn trust(path: &Path, name: &str, add: bool) -> Result<bool> {
    let text = std::fs::read_to_string(path).unwrap_or_default();
    let mut table: toml::Table =
        toml::from_str(&text).map_err(|e| Error::Refused(format!("{} does not parse: {}", path.display(), e.message())))?;
    let gated = table.get("harness").and_then(|h| h.get(name)).and_then(|c| c.get("gated")).and_then(|g| g.as_bool());
    if add == (gated == Some(true)) {
        return Ok(false);
    }
    let harness = table.entry("harness").or_insert_with(|| toml::Value::Table(toml::Table::new()));
    let Some(harness) = harness.as_table_mut() else {
        return Err(Error::Refused(format!("`harness` in {} is not a table", path.display())));
    };
    if add {
        let mut entry = toml::Table::new();
        entry.insert("gated".into(), true.into());
        harness.insert(name.into(), entry.into());
    } else {
        harness.remove(name);
    }
    write_atomic(path, &toml::to_string(&table).expect("table serializes"))?;
    Ok(true)
}

fn write_extension(file: &Path, text: &str) -> Result<bool> {
    // A link is replaced, never written through, as for the skill.
    if file.symlink_metadata().is_ok_and(|m| m.file_type().is_symlink()) {
        std::fs::remove_file(file).map_err(io(file))?;
    }
    if std::fs::read_to_string(file).is_ok_and(|t| t == text) {
        return Ok(false);
    }
    write_atomic(file, text)?;
    Ok(true)
}

fn remove_extension(file: &Path) -> Result<bool> {
    let ours =
        file.symlink_metadata().is_ok_and(|m| m.is_file()) && std::fs::read_to_string(file).is_ok_and(|t| t.starts_with(EXTENSION_MARKER));
    if !ours {
        return Ok(false);
    }
    std::fs::remove_file(file).map_err(io(file))?;
    Ok(true)
}

fn remove_command(file: &Path) -> Result<bool> {
    let ours =
        file.symlink_metadata().is_ok_and(|m| m.is_file()) && std::fs::read_to_string(file).is_ok_and(|t| t.contains(COMMAND_MARKER));
    if !ours {
        return Ok(false);
    }
    std::fs::remove_file(file).map_err(io(file))?;
    Ok(true)
}

fn write_skill(dir: &Path, skill: &str) -> Result<bool> {
    // A link is replaced, never written through, so a folder elsewhere stays untouched.
    if dir.symlink_metadata().is_ok_and(|m| m.file_type().is_symlink()) {
        std::fs::remove_file(dir).map_err(io(dir))?;
    }
    let file = dir.join("SKILL.md");
    if std::fs::read_to_string(&file).is_ok_and(|t| t == skill) {
        return Ok(false);
    }
    write_atomic(&file, skill)?;
    Ok(true)
}

fn remove_skill(dir: &Path) -> Result<bool> {
    if dir.symlink_metadata().is_ok_and(|m| m.file_type().is_symlink()) {
        return Ok(false);
    }
    let file = dir.join("SKILL.md");
    if !file.is_file() {
        return Ok(false);
    }
    std::fs::remove_file(&file).map_err(io(&file))?;
    let _ = std::fs::remove_dir(dir);
    Ok(true)
}

/// Runs the steps. Every settings file is parsed first, so an invalid one stops the install before any write.
pub fn apply(steps: &[Step], skill: &str) -> Result<Vec<Change>> {
    for s in steps {
        if let Step::AddAskRule { settings }
        | Step::RemoveAskRule { settings }
        | Step::AddHooks { settings, .. }
        | Step::RemoveHooks { settings } = s
        {
            read_settings(settings)?;
        }
    }
    let mut out = vec![];
    for s in steps {
        let effect = match s {
            Step::WriteSkill { dir } => changed(write_skill(dir, skill)?, Effect::Written),
            Step::RemoveSkill { dir } => changed(remove_skill(dir)?, Effect::Removed),
            Step::AddAskRule { settings } => changed(ask_rule(settings, true)?, Effect::Written),
            Step::RemoveAskRule { settings } => changed(ask_rule(settings, false)?, Effect::Written),
            Step::AddHooks { settings, bin } => changed(hooks(settings, Some(bin))?, Effect::Written),
            Step::RemoveHooks { settings } => changed(hooks(settings, None)?, Effect::Written),
            Step::WriteExtension { file, text } => changed(write_extension(file, text)?, Effect::Written),
            Step::RemoveExtension { file } => changed(remove_extension(file)?, Effect::Removed),
            Step::WriteCommand { file, text } => changed(write_extension(file, text)?, Effect::Written),
            Step::RemoveCommand { file } => changed(remove_command(file)?, Effect::Removed),
            Step::Trust { file, name } => changed(trust(file, name, true)?, Effect::Written),
            Step::Untrust { file, name } => changed(trust(file, name, false)?, Effect::Written),
        };
        let path = s.file();
        match out.iter_mut().find(|c: &&mut Change| c.path == path) {
            Some(c) if c.effect == Effect::Unchanged => c.effect = effect,
            Some(_) => {}
            None => out.push(Change { path, effect }),
        }
    }
    Ok(out)
}

fn changed(did: bool, effect: Effect) -> Effect {
    if did { effect } else { Effect::Unchanged }
}

/// For pi and omp: whether the extension file exists, and whether it equals the built-in one.
pub fn extension_status(h: Harness, home: &Path) -> Option<(bool, bool)> {
    let file = h.extension_file(home)?;
    Some(match std::fs::read_to_string(file) {
        Ok(t) => (true, t == h.extension()),
        Err(_) => (false, false),
    })
}

/// Whether the skill file of `h` exists, and whether it equals the built-in skill.
pub fn status(h: Harness, home: &Path) -> (bool, bool) {
    match std::fs::read_to_string(h.skill_dir(home).join("SKILL.md")) {
        Ok(t) => (true, t == SKILL),
        Err(_) => (false, false),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn setup() -> (tempfile::TempDir, PathBuf, PathBuf) {
        let dir = tempfile::tempdir().unwrap();
        let home = dir.path().join("home");
        let cfg = dir.path().join("cfg");
        for h in [".claude", ".pi"] {
            std::fs::create_dir_all(home.join(h)).unwrap();
        }
        (dir, home, cfg)
    }

    #[test]
    fn detection_and_names() {
        let (_d, home, _) = setup();
        let found: Vec<&str> = Harness::ALL.iter().filter(|h| h.detected(&home)).map(|h| h.name()).collect();
        assert_eq!(found, ["claude", "pi"]);
        assert_eq!(Harness::parse("omp"), Some(Harness::Omp));
        assert_eq!(Harness::parse("vscode"), None);
    }

    #[test]
    fn install_merges_and_is_idempotent() {
        let (_d, home, cfg) = setup();
        let settings = home.join(".claude/settings.json");
        std::fs::write(&settings, "{\"theme\": \"dark\", \"permissions\": {\"ask\": [\"Bash(rm:*)\"], \"defaultMode\": \"auto\"}}")
            .unwrap();
        let steps = plan(&home, &cfg, &[Harness::Claude, Harness::Pi], false);
        assert_eq!(steps.len(), 9);
        let changes = apply(&steps, "SKILL TEXT").unwrap();
        assert!(changes.iter().all(|c| c.effect == Effect::Written), "{changes:?}");
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(v["theme"], "dark");
        assert_eq!(v["permissions"]["defaultMode"], "auto");
        assert_eq!(v["permissions"]["ask"], serde_json::json!(["Bash(rm:*)", ASK_RULE]));
        assert!(std::fs::read_to_string(cfg.join("trust.toml")).unwrap().contains("gated = true"));
        assert_eq!(std::fs::read_to_string(home.join(".pi/agent/skills/rkb/SKILL.md")).unwrap(), "SKILL TEXT");
        let retro = home.join(".claude/commands/rkb-retro.md");
        assert_eq!(std::fs::read_to_string(&retro).unwrap(), COMMANDS[0].1);
        std::fs::write(home.join(".claude/commands/mine.md"), "the user's own command").unwrap();

        let again = apply(&steps, "SKILL TEXT").unwrap();
        assert!(again.iter().all(|c| c.effect == Effect::Unchanged), "{again:?}");
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(v["permissions"]["ask"].as_array().unwrap().len(), 2);

        let removed = apply(&plan(&home, &cfg, &[Harness::Claude], true), "SKILL TEXT").unwrap();
        assert_eq!(removed[0].effect, Effect::Removed);
        assert!(!retro.exists() && !home.join(".claude/commands/rkb-distill.md").exists());
        assert!(home.join(".claude/commands/mine.md").exists(), "only rkb's command files are removed");
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!((v["permissions"]["ask"].clone(), v["theme"].clone()), (serde_json::json!(["Bash(rm:*)"]), serde_json::json!("dark")));
        assert!(!std::fs::read_to_string(cfg.join("trust.toml")).unwrap().contains("claude-code"));
        assert!(!home.join(".claude/skills/rkb").exists());
    }

    #[test]
    fn uninstall_leaves_no_empty_permissions() {
        let (_d, home, cfg) = setup();
        let settings = home.join(".claude/settings.json");
        std::fs::write(&settings, "{\"theme\": \"dark\"}").unwrap();
        apply(&plan(&home, &cfg, &[Harness::Claude], false), "S").unwrap();
        apply(&plan(&home, &cfg, &[Harness::Claude], true), "S").unwrap();
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(v, serde_json::json!({"theme": "dark"}));
    }

    #[test]
    fn hooks_merge_and_uninstall_keep_user_hooks() {
        let (_d, home, cfg) = setup();
        let settings = home.join(".claude/settings.json");
        let mine = serde_json::json!({ "hooks": [{ "type": "command", "command": "echo hi" }] });
        std::fs::write(&settings, serde_json::json!({ "model": "x", "hooks": { "SessionStart": [mine.clone()] } }).to_string()).unwrap();
        let steps = plan(&home, &cfg, &[Harness::Claude], false);
        apply(&steps, "S").unwrap();
        assert!(hooks_installed(&home));
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(v["model"], "x");
        assert_eq!(v["hooks"]["SessionStart"][0], mine);
        assert_eq!(v["hooks"]["SessionStart"][1]["hooks"][0]["command"], format!("{} hook session-start", hook_binary()));
        assert_eq!(v["hooks"]["PostToolUseFailure"][0]["matcher"], "Bash");
        assert_eq!(v["hooks"]["PostToolUseFailure"][0]["hooks"][0]["timeout"], 5);
        assert_eq!(v["hooks"].as_object().unwrap().len(), 8);
        assert_eq!(v["hooks"]["PreCompact"][0]["hooks"][0]["command"], format!("{} hook pre-compact", hook_binary()));
        assert_eq!(v["hooks"]["SessionEnd"][0]["hooks"][0]["command"], format!("{} hook session-end", hook_binary()));

        let again = apply(&steps, "S").unwrap();
        assert!(again.iter().all(|c| c.effect == Effect::Unchanged), "{again:?}");
        assert_eq!(again.iter().filter(|c| c.path == settings).count(), 1, "one row per file");

        apply(&plan(&home, &cfg, &[Harness::Claude], true), "S").unwrap();
        assert!(!hooks_installed(&home));
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(v, serde_json::json!({ "model": "x", "hooks": { "SessionStart": [mine] } }));
    }

    #[test]
    fn extension_install_and_uninstall() {
        let (d, home, cfg) = setup();
        let ext = home.join(".pi/agent/extensions/rkb.ts");
        apply(&plan(&home, &cfg, &[Harness::Claude, Harness::Pi], false), "S").unwrap();
        let text = std::fs::read_to_string(&ext).unwrap();
        assert!(text.starts_with(EXTENSION_MARKER) && text.contains("const HARNESS = \"pi\"") && !text.contains("__HARNESS__"));
        assert_eq!(extension_status(Harness::Pi, &home), Some((true, true)));
        assert_eq!(extension_status(Harness::Claude, &home), None);
        let trust_file = std::fs::read_to_string(cfg.join("trust.toml")).unwrap();
        assert!(trust_file.contains("[harness.pi]") && trust_file.contains("[harness.claude-code]"), "{trust_file}");

        let again = apply(&plan(&home, &cfg, &[Harness::Pi], false), "S").unwrap();
        assert!(again.iter().all(|c| c.effect == Effect::Unchanged), "{again:?}");

        let bin = serde_json::to_string(&hook_binary()).unwrap();
        assert!(text.contains(&format!("const RKB: string = {bin};")) && !text.contains("__RKB__"), "{text}");
        std::fs::write(&ext, text.replace(&bin, "\"/old/place/rkb\"")).unwrap();
        let repaired = apply(&plan(&home, &cfg, &[Harness::Pi], false), "S").unwrap();
        assert!(repaired.iter().any(|c| c.path == ext && c.effect == Effect::Written), "a changed binary path is rewritten");
        assert_eq!(std::fs::read_to_string(&ext).unwrap(), text);

        apply(&plan(&home, &cfg, &[Harness::Pi], true), "S").unwrap();
        assert!(!ext.exists());
        let trust_file = std::fs::read_to_string(cfg.join("trust.toml")).unwrap();
        assert!(!trust_file.contains("[harness.pi]") && trust_file.contains("[harness.claude-code]"), "{trust_file}");

        std::fs::create_dir_all(ext.parent().unwrap()).unwrap();
        std::fs::write(&ext, "// my own extension\n").unwrap();
        apply(&plan(&home, &cfg, &[Harness::Pi], true), "S").unwrap();
        assert_eq!(std::fs::read_to_string(&ext).unwrap(), "// my own extension\n", "not rkb's, so kept");

        let elsewhere = d.path().join("elsewhere.ts");
        std::fs::write(&elsewhere, "linked").unwrap();
        std::fs::remove_file(&ext).unwrap();
        std::os::unix::fs::symlink(&elsewhere, &ext).unwrap();
        apply(&plan(&home, &cfg, &[Harness::Pi], false), "S").unwrap();
        assert!(!ext.symlink_metadata().unwrap().file_type().is_symlink());
        assert_eq!(std::fs::read_to_string(&elsewhere).unwrap(), "linked");
    }

    #[test]
    fn link_is_replaced_not_followed() {
        let (d, home, cfg) = setup();
        let elsewhere = d.path().join("repo/skills/rkb");
        std::fs::create_dir_all(&elsewhere).unwrap();
        std::fs::write(elsewhere.join("SKILL.md"), "repo copy").unwrap();
        std::fs::create_dir_all(home.join(".claude/skills")).unwrap();
        std::os::unix::fs::symlink(&elsewhere, home.join(".claude/skills/rkb")).unwrap();
        apply(&plan(&home, &cfg, &[Harness::Claude], false), "SKILL TEXT").unwrap();
        let link = home.join(".claude/skills/rkb");
        assert!(!link.symlink_metadata().unwrap().file_type().is_symlink());
        assert_eq!(std::fs::read_to_string(link.join("SKILL.md")).unwrap(), "SKILL TEXT");
        assert_eq!(std::fs::read_to_string(elsewhere.join("SKILL.md")).unwrap(), "repo copy");
    }

    #[test]
    fn invalid_settings_stop_before_any_write() {
        let (_d, home, cfg) = setup();
        std::fs::write(home.join(".claude/settings.json"), "{ not json").unwrap();
        let e = apply(&plan(&home, &cfg, &[Harness::Pi, Harness::Claude], false), "SKILL TEXT").unwrap_err();
        assert!(e.to_string().contains("settings.json"), "{e}");
        assert!(!home.join(".pi/agent/skills/rkb/SKILL.md").exists());
    }

    #[test]
    fn missing_settings_file_is_created() {
        let (_d, home, cfg) = setup();
        apply(&plan(&home, &cfg, &[Harness::Claude], false), "S").unwrap();
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(home.join(".claude/settings.json")).unwrap()).unwrap();
        assert_eq!(v["permissions"]["ask"], serde_json::json!([ASK_RULE]));
    }

    #[test]
    fn command_body_drops_the_frontmatter() {
        let body = command_body(COMMANDS[1].1);
        assert!(body.starts_with("Turn rkb inbox items into lessons."), "{body}");
        assert!(body.contains("rkb inbox done") && body.contains("[tool output]"));
        for (_, text) in COMMANDS {
            assert!(text.contains(COMMAND_MARKER), "the marker is in the frontmatter");
            assert!(!command_body(text).contains("generated-by") && !command_body(text).contains("<!--"), "the model never sees it");
        }
    }

    #[test]
    fn hook_binary_and_path_repair() {
        let d = tempfile::tempdir().unwrap();
        let (a, b) = (d.path().join("a"), d.path().join("b"));
        for dir in [&a, &b] {
            std::fs::create_dir_all(dir).unwrap();
            std::fs::write(dir.join("rkb"), "").unwrap();
        }
        let path = std::env::join_paths([&a, &b]).unwrap();
        assert_eq!(hook_binary_with(Some(&path), Some(&a.join("rkb"))), "rkb", "the rkb on PATH is this binary");
        let other = hook_binary_with(Some(&path), Some(&b.join("rkb")));
        assert_eq!(other, b.join("rkb").canonicalize().unwrap().display().to_string(), "another rkb comes first on PATH");

        let settings = d.path().join("settings.json");
        let old = serde_json::json!({ "hooks": { "Stop": [
            { "hooks": [{ "type": "command", "command": "/old/place/rkb hook stop", "timeout": 5 }] },
            { "hooks": [{ "type": "command", "command": "my-own stop hook" }] }
        ] } });
        std::fs::write(&settings, old.to_string()).unwrap();
        assert!(hooks(&settings, Some(&other)).unwrap());
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        let stop = v["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 2, "repaired in place, not added: {v}");
        assert_eq!(stop[0]["hooks"][0]["command"], format!("{other} hook stop"));
        assert_eq!(stop[1]["hooks"][0]["command"], "my-own stop hook");
        assert_eq!(v["hooks"]["SessionEnd"][0]["hooks"][0]["command"], format!("{other} hook session-end"));
        assert!(!hooks(&settings, Some(&other)).unwrap(), "idempotent");
        assert!(hooks(&settings, None).unwrap());
        let v: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(v, serde_json::json!({ "hooks": { "Stop": [{ "hooks": [{ "type": "command", "command": "my-own stop hook" }] }] } }));
    }
}
